---
title: "cma-week3"
author: "Yves Gubelmann"
date: "7 5 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readr)        # to import tabular data (e.g. csv)
library(dplyr)        # to manipulate (tabular) data
library(ggplot2)      # to visualize data
library(sf)           # to handle spatial vector data
library(terra)        # To handle raster data
library(lubridate)    # To handle dates and times
library(zoo)          # To smoothen data
library(cowplot)
library(SimilarityMeasures)

# define functions
rle_id <- function(vec){
  x <- rle(vec)$lengths
  as.factor(rep(seq_along(x), times=x))
  }

```


```{r task 1, highlight=TRUE, message = FALSE}
# Task 1
caro <- read_delim("00_Rawdata/caro60.csv",",") # adjust path
caro <- st_as_sf(caro, coords = c("E", "N"), crs = 2056, remove = FALSE)

caro <- caro %>%                           # Take caro (grouping not needed)
  mutate(timelag = as.integer(difftime(lead(DatetimeUTC),DatetimeUTC, units = "secs"))) %>% 
  mutate(steplength = sqrt(((E-lead(E,1))^2+(N-lead(N,1))^2))) %>%
  # Step a:  calculate the following Euclidean distance
  mutate(speed = steplength/timelag) %>% 
  # Step b: Measure the distance from every point to every other point within this temporal window
  mutate(
    nMinus3 = sqrt((lag(E, 3) - E)^2 + (lag(N, 3) - N)^2),
    nMinus2 = sqrt((lag(E, 2) - E)^2 + (lag(N, 2) - N)^2),
    nMinus1 = sqrt((lag(E, 1) - E)^2 + (lag(N, 1) - N)^2),
    nPlus1 = sqrt((E - lead(E, 1))^2 + (N - lead(N, 1))^2),
    nPlus2 = sqrt((E - lead(E, 2))^2 + (N - lead(N, 2))^2),
    nPlus3 = sqrt((E - lead(E, 3))^2 + (N - lead(N, 3))^2)
  ) %>% 
  rowwise() %>%
  mutate(
    stepMean = mean(c(nMinus3, nMinus2, nMinus1,nPlus1,nPlus2, nPlus3))
  ) %>%
  ungroup() 
# Task 2
# Step c: Remove static points
caro <- caro %>% 
  ungroup() %>%
  mutate(static = stepMean < mean(stepMean, na.rm = TRUE))

caro_filter <- caro %>%
  filter(!static)
# Task 3
caro_filter %>%
  ggplot(data=caro, mapping=aes(E, N, colour = static))  +
  geom_path() +
  geom_point() +
  coord_fixed() +
  theme(legend.position = "bottom") +
  theme_classic()
```


```{r task 4, highlight=TRUE, message = FALSE}
# Task 4: Segment-based analysis
caro <- caro %>%
  mutate(segment_id = rle_id(static))

# generate a plot with uncleanded data
caro_filter %>%
  ggplot(data=caro, mapping=aes(E, N, colour = segment_id))  +
  # removed the following line because it plots only some lines. looks ugly
  # geom_path() +
  geom_point() +
  coord_equal() +
  labs(title = "Moving segements coloured by segment ID (uncleaned)") + 
  theme_classic() +
  theme(legend.position = "none")

# filter on duration
caro_5 <- caro %>%
  group_by(segment_id) %>% 
  mutate(n = n()) 

# generate a plot with sliced data
caro_5 %>%
  filter(!static & n >5) %>% 
  ggplot(aes(E, N)) +
  geom_path() +
  geom_point() +
  coord_fixed() +
  labs(title = "Moving segements coloured by segment ID (sliced)") + 
  theme_classic() +
  theme(legend.position = "none")
```

```{r task 5, highlight=TRUE, message = FALSE}
# Task 5: Similarity measures
ped <- read_delim("00_Rawdata/pedestrian.csv",",") # adjust path
ped <- st_as_sf(ped, coords = c("E", "N"), crs = 2056, remove = FALSE)
ped <- ped %>% mutate(trajectories = as.factor(ped$TrajID)) 

ped %>%
  ggplot(data=ped, mapping=aes(E, N, colour = trajectories))  +
  geom_path() +
  geom_point() +
  coord_fixed() +
  facet_wrap(~trajectories) +
  labs(title = "Visual Comparision of the 6 trajectories", subtitle = "Each subplot is shown i a different graph") + 
  theme_classic()
```

```{r task_6, highlight=TRUE, message = FALSE}
# Task 6: Calculate similarity
# filter by trajectory
ped1 <- ped %>% 
  filter(trajectories == 1) %>% 
  dplyr::select(E,N)
ped2 <- ped %>%
  filter(trajectories == 2) %>% 
  dplyr::select(E,N) 
ped3 <- ped %>%
  filter(trajectories == 3) %>% 
  dplyr::select(E,N) 
ped4 <- ped %>%
  filter(trajectories == 4) %>% 
  dplyr::select(E,N) 
ped5 <- ped %>%
  filter(trajectories == 5) %>% 
  dplyr::select(E,N) 
ped6 <- ped %>%
  filter(trajectories == 6) %>% 
  dplyr::select(E,N) 
# convert into matrix
ped1m <- matrix(data = c(as.numeric(ped1$E),as.numeric(ped1$N)), ncol = 2)
ped2m <- matrix(data = c(as.numeric(ped2$E),as.numeric(ped2$N)), ncol = 2)
ped3m <- matrix(data = c(as.numeric(ped3$E),as.numeric(ped3$N)), ncol = 2)
ped4m <- matrix(data = c(as.numeric(ped4$E),as.numeric(ped4$N)), ncol = 2)
ped5m <- matrix(data = c(as.numeric(ped5$E),as.numeric(ped5$N)), ncol = 2)
ped6m <- matrix(data = c(as.numeric(ped6$E),as.numeric(ped6$N)), ncol = 2)
# compute similarity measure: EditDist
ed2 <- EditDist(ped1m,ped2m)
ed3 <- EditDist(ped1m,ped3m)
ed4 <- EditDist(ped1m,ped4m)
ed5 <- EditDist(ped1m,ped5m)
ed6 <- EditDist(ped1m,ped6m)
# compute similarity measure: DTW
dtw2 <- DTW(ped1m,ped2m)
dtw3 <- DTW(ped1m,ped3m)
dtw4 <- DTW(ped1m,ped4m)
dtw5 <- DTW(ped1m,ped5m)
dtw6 <- DTW(ped1m,ped6m)
# Add computed results to ped
ped <- ped %>% 
  mutate(
    dtw = case_when(
      trajectories == "2"~dtw2,
      trajectories == "3"~dtw3,
      trajectories == "4"~dtw4,
      trajectories == "5"~dtw5,
      trajectories == "6"~dtw6,
      TRUE~0 #Default case
    )
  ) %>% 
  mutate(
  ed = case_when(
    trajectories == "2"~ed2,
    trajectories == "3"~ed3,
    trajectories == "4"~ed4,
    trajectories == "5"~ed5,
    trajectories == "6"~ed6,
    TRUE~0 #Default case
    )
  )
# plot dtw analysis
p_dtw <- ggplot(ped, aes(x = trajectories, y = dtw, fill = trajectories)) +
  geom_col() +
  # For some reason it plots the sum of the computed similarity measures
  scale_y_continuous(limits = c(0, 600000)) +
  theme_classic() +
  labs(title = "computed similarity: DTW") +
  theme(legend.position = "none")

# plot edist analysis
p_ed <- ggplot(ped, aes(x = trajectories, y = ed,  fill = trajectories)) +
  geom_col() +
  # For some reason it works in this plot 
  scale_y_continuous(limits = c(0, 50)) +
  theme_classic() +
  labs(title = "computed similarity: Edist") +
  theme(legend.position = "none")

# plot it in one row
cowplot::plot_grid(p_dtw, p_ed, nrow = 1, ncol = 2)
```


